site_name: GenLM-Agent documentation
site_url: https://darbotlm.github.io/genlm-agent/

theme:
  name: material

nav:
  - Overview: index.md
  - Usage:
      - Hello world: usage/hello_world.md
      - Task engine: usage/task_engine.md
  - API:
      - Agent: reference/agent.md
      - Task engine: reference/task_engine.md
      - Verification: reference/verification.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [glmagent]
          options:
            merge_init_into_class: true
            show_root_heading: true
            members_order: source
            filters:
              - "!^_"

repo_url: https://github.com/DarbotLM/genlm-agent
repo_name: DarbotLM/genlm-agent
